### ISSUE TITLE
How do we implement NGApplication.isDevelopmentMode()?

### ISSUE THREAD

**Issue by paulhoadley** [ngobjects/ng-objects#6]
As noted in the method itself, checking `user.name` is not the final implementation! So how does `ERXApplication` do it? Several steps:

1. if `er.extensions.ERXApplication.developmentMode` property is set, use its value; else
2. if `WOIDE` property is set to `WOLips` or `Xcode`, return `true`; else
3. return the value of `NSProjectBundleEnabled` property.

I think the only candidate for this project would be explicitly setting a property, as in 1 above. As far as I know, there's no magic for detecting that an app was "launched from Eclipse", and none of those other properties are relevant to us.

I take it that property handling is in a bit of flux for now? Shelve this for the moment?

**Comment by hugith** [comment]
I agree that it should probably be an explicit property.

For now I've changed `isDevelopmentMode()` to be based on the Property `WOMonitorEnabled` which is set to `YES` when applications are started by wotaskd. This means apps will default to "development mode" unless explicitly told otherwise.

**Comment by hugith** [comment]
Closing for now, even if `NGProperties` might not end up being the final resting place, and this might not be the final implementation, I do think it's an acceptable compromise for the next while, agreed?
